apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: localproduction
  namespace: default
spec:
  secretName: localproduction-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "*.local.<your domain>"
  dnsNames:
  - "local.<your domain>"
  - "*.local.<your domain>"